# __Basic Python__ 
#### _Name: Priyanka M_
#### _Register Number: 311019104066_


###  1. Split this string

In [49]:
s = "Hi there Sam!"

In [50]:
# split string
s = s.split()
print(s)

['Hi', 'there', 'Sam!']


### 2. Use .format() to print the following string.
##### Output should be: The diameter of Earth is 12742 kilometers.

In [51]:
planet = "Earth"
diameter = 12742

In [52]:

print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


### 3. In this nest dictionary grab the word "hello"

In [53]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [54]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


## Numpy

In [55]:
import numpy as np

### 4.1 Create an array of 10 zeros?

In [56]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4.2 Create an array of 10 fives?

In [57]:
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### 5. Create an array of all the even integers from 20 to 35

In [58]:
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


### 6. Create a 3x3 matrix with values ranging from 0 to 8

In [59]:
array=np.arange(0,9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 7. Concatenate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [60]:
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
c=np.concatenate((a,b))
print("a=",a)
print("b=",b)
print("c=",c)



a= [1 2 3]
b= [4 5 6]
c= [1 2 3 4 5 6]


## Pandas

### 8. Create a dataframe with 3 rows and 2 columns

In [68]:
import pandas as pd
import numpy as np
rows=[['a','aa'],['b', 'bb'],['c','cc']]
dtf=pd.DataFrame(rows,columns=['I','II'])
print(dtf)

   I  II
0  a  aa
1  b  bb
2  c  cc


### 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [62]:
from time import strftime
import pandas as pd
import datetime
ts=pd.date_range(start='01/01/2023',end='02/10/2013')
print(ts, strftime("%d-%m-%y"))

DatetimeIndex([], dtype='datetime64[ns]', freq='D') 31-10-22


### 10. Create 2D list to DataFrame
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [64]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
print(lists)

[[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]


In [66]:
data= [['aaa',22],['bbb',25],['ccc',24]]
df=pd.DataFrame(data,columns=['name','age'])
print(df)

  name  age
0  aaa   22
1  bbb   25
2  ccc   24
