# __Basic Python__ 
#### _Name: Priyanka M_
#### _Register Number: 311019104066_


###  1. Split this string

In [4]:
s = "Hi there Sam!"

In [5]:
# split string
s = s.split()
print(s)

['Hi', 'there', 'Sam!']


### 2. Use .format() to print the following string.
##### Output should be: The diameter of Earth is 12742 kilometers.

In [6]:
planet = "Earth"
diameter = 12742

In [7]:

print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


### 3. In this nest dictionary grab the word "hello"

In [23]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [22]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


## Numpy

In [38]:
import numpy as np

### 4.1 Create an array of 10 zeros?

In [31]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4.2 Create an array of 10 fives?

In [30]:
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### 5. Create an array of all the even integers from 20 to 35

In [29]:
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


### 6. Create a 3x3 matrix with values ranging from 0 to 8

In [35]:
array=np.arange(0,9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 7. Concatenate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [48]:
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
c=np.concatenate((a,b))
print("a=",a)
print("b=",b)
print("c=",c)



a= [1 2 3]
b= [4 5 6]
c= [1 2 3 4 5 6]


## Pandas

### 8. Create a dataframe with 3 rows and 2 columns

In [59]:
import pandas as pd


ImportError: this version of pandas is incompatible with numpy < 1.20.3
your numpy version is 1.19.5.
Please upgrade numpy to >= 1.20.3 to use this pandas version